In [1]:
import numpy as np

## The NumPy ndarray: A Multidimensional Array Object

An ndarray is a generic multidimensional container for homogeneous data: all of the lements must be the same type

In [2]:
data = np.random.rand(2, 3)
data

array([[ 0.85410415,  0.19079579,  0.49750555],
       [ 0.97735   ,  0.46095328,  0.81099994]])

In [3]:
data * 10 # Vectorized/Broadcast multiplication

array([[ 8.54104146,  1.90795791,  4.97505547],
       [ 9.77350005,  4.6095328 ,  8.10999944]])

In [4]:
data + data # Vectorized/Broadcast addition

array([[ 1.70820829,  0.38159158,  0.99501109],
       [ 1.95470001,  0.92190656,  1.62199989]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

### Creating ndarrays

Create ndarrays using **np.array()** function, which accepts any sequence-like objects (python lists, or other arrays)

In [7]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [8]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 4)

Unless explicitly specified, **np.array** tries to infer a good data type for the array that it creates. The data type is stored in a special **dtype** object:

In [11]:
arr1.dtype

dtype('float64')

In [12]:
arr2.dtype

dtype('int64')

**np.zeros()** and **np.ones()** create arrays of 0's or 1's, respectively, with a given length or shape. **np.empty()** creates an array without initializing its values to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape:

In [13]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.zeros((3, 6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [15]:
np.empty((2, 3, 2))

array([[[  1.61100420e-316,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

**np.arange()** is an array-valued version of the built-in Python range function:

In [16]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
np.ones_like(arr2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### Data Types for ndarrays

**dtype** is a special object containing the information the ndarray needs to interpret a chunk of memory as a particular type of data:

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

Explicitly cast an array from one dtype to another using **np.astype()**

In [23]:
float_arr = arr.astype(np.float64) # int to float
float_arr.dtype

dtype('float64')

In [24]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([  3.7,  -1.2,  -2.6,   0.5,  12.9,  10.1])

In [25]:
arr.astype(np.int32) # float to int, decimal part truncated

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

Use **np.astype()** to convert strings to numeric form. Casting will raise a **TypeError** if fails.

In [26]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([  1.25,  -9.6 ,  42.  ])

Use another array's dtype attribute:

In [27]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

There are shorthand type code strings you can also use to refer to a dtype:

In [28]:
empty_uint32 = np.empty(8, dtype='u4') # us = uint32
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

Calling **astype** *always* creates a new array (a copy of the data), even if the new dtype is the same as the old dtype.

### Operations between Arrays and Scalars

Vectorization: express batch operations on data without writing any for loops. Any arithmetic operations between equal-size arrays applies the operation elementwise:

In [29]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [30]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [31]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Arithmetic operations with scalars are propagating the value to each element:

In [32]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [33]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

### Basic Indexing and Slicing

Indexing and slicing on nne-dimensional arrays are similar to Python lists:

In [34]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr[5]

5

In [36]:
arr[5:8]

array([5, 6, 7])

if you assign a scalar value to a slice, as in **arr[5:8] = 12**, the value is propagated (or **broadcasted** henceforth) to the entire selection.

In [37]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

An important first distinction from lists is that array slices are *views* (like **pointer**) on the original array. This means that the data is not copied, and any modifications to the view will be reflected in the source array:

In [38]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [39]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

1. View of array: arra[5:8]
2. Copy of array: **arr[5:8].copy()**

In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [40]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [41]:
arr2d[0][2] # individual elements can be accessed recursively

3

In [42]:
arr2d[0, 2] # Or a comma-separated list of indices

3

In [43]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [44]:
arr3d.ndim # 3-dimensional array

3

In [45]:
arr3d[0] # 2-dimensional array

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
old_values = arr3d[0].copy()

In [47]:
arr3d[0] = 42 # arr3d[0] is a 2-D array, so 42 is propagated 
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

**arr3d[1, 0]** gives you all of the values whose indices start with **(1, 0)**

In [49]:
arr3d[1, 0] # 1-D array

array([7, 8, 9])

#### Indexing with slices

Slices on ndarrays are always views (i.e. **pointer**)

In [50]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [51]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [52]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr2d[:2] # sliced along axis 0, the first axis

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2d[:2, 1:] # mpass multiple slices

array([[2, 3],
       [5, 6]])

In [55]:
arr2d[1, :2]

array([4, 5])

In [56]:
arr2d[2, :1]

array([7])

In [57]:
arr2d[2:, :1]

array([[7]])

In [58]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [59]:
arr2d[:2, 1:] = 0 # propagated assignment
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [60]:
data = np.random.randn(7, 4)
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data

array([[-0.68852517,  0.06928954, -0.38033293, -2.44130041],
       [ 0.87543295,  1.10456624,  0.32148621, -0.93581019],
       [ 1.16004728,  1.45457726,  1.74108522, -0.03413723],
       [ 0.4114707 , -1.04874225, -1.00763815,  2.0107912 ],
       [-0.76702742,  0.44005024, -0.56695151, -0.09113811],
       [ 0.95706444, -1.17156395,  0.44799262,  1.00290634],
       [ 0.05020417,  0.43837211, -0.10377714,  0.9917559 ]])

In [61]:
# vectorized comparison, producing ndarray of bool
# must be of the same length as the axis it's indexing

names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [62]:
data[names == 'Bob'] # Using bool ndarray to index the rows (axis=0)

array([[-0.68852517,  0.06928954, -0.38033293, -2.44130041],
       [ 0.4114707 , -1.04874225, -1.00763815,  2.0107912 ]])

In [63]:
# Mix and match boolean arrays with slices or integers

data[names == 'Bob', 2:] 

array([[-0.38033293, -2.44130041],
       [-1.00763815,  2.0107912 ]])

In [64]:
data[names == 'Bob', 3]

array([-2.44130041,  2.0107912 ])

In [65]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [66]:
data[names != 'Bob']

array([[ 0.87543295,  1.10456624,  0.32148621, -0.93581019],
       [ 1.16004728,  1.45457726,  1.74108522, -0.03413723],
       [-0.76702742,  0.44005024, -0.56695151, -0.09113811],
       [ 0.95706444, -1.17156395,  0.44799262,  1.00290634],
       [ 0.05020417,  0.43837211, -0.10377714,  0.9917559 ]])

In [67]:
data[~(names == 'Bob')] # Or equivalently

array([[ 0.87543295,  1.10456624,  0.32148621, -0.93581019],
       [ 1.16004728,  1.45457726,  1.74108522, -0.03413723],
       [-0.76702742,  0.44005024, -0.56695151, -0.09113811],
       [ 0.95706444, -1.17156395,  0.44799262,  1.00290634],
       [ 0.05020417,  0.43837211, -0.10377714,  0.9917559 ]])

Operation on bool ndarray of the same size ("**and**", "**or**" in python don't work here):
1. **|**: or
2. **&**: and

In [68]:
mask = (names == 'Bob') | (names == 'Will') 
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [69]:
data[mask]

array([[-0.68852517,  0.06928954, -0.38033293, -2.44130041],
       [ 1.16004728,  1.45457726,  1.74108522, -0.03413723],
       [ 0.4114707 , -1.04874225, -1.00763815,  2.0107912 ],
       [-0.76702742,  0.44005024, -0.56695151, -0.09113811]])

In [70]:
data

array([[-0.68852517,  0.06928954, -0.38033293, -2.44130041],
       [ 0.87543295,  1.10456624,  0.32148621, -0.93581019],
       [ 1.16004728,  1.45457726,  1.74108522, -0.03413723],
       [ 0.4114707 , -1.04874225, -1.00763815,  2.0107912 ],
       [-0.76702742,  0.44005024, -0.56695151, -0.09113811],
       [ 0.95706444, -1.17156395,  0.44799262,  1.00290634],
       [ 0.05020417,  0.43837211, -0.10377714,  0.9917559 ]])

In [71]:
data < 0 # Multi-dimensional bool array

array([[ True, False,  True,  True],
       [False, False, False,  True],
       [False, False, False,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True],
       [False,  True, False, False],
       [False, False,  True, False]], dtype=bool)

In [72]:
data[data < 0] = 0    
data

array([[ 0.        ,  0.06928954,  0.        ,  0.        ],
       [ 0.87543295,  1.10456624,  0.32148621,  0.        ],
       [ 1.16004728,  1.45457726,  1.74108522,  0.        ],
       [ 0.4114707 ,  0.        ,  0.        ,  2.0107912 ],
       [ 0.        ,  0.44005024,  0.        ,  0.        ],
       [ 0.95706444,  0.        ,  0.44799262,  1.00290634],
       [ 0.05020417,  0.43837211,  0.        ,  0.9917559 ]])

In [73]:
data[names != 'Joe'] = 7 # vectorized value assignment
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.87543295,  1.10456624,  0.32148621,  0.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.95706444,  0.        ,  0.44799262,  1.00290634],
       [ 0.05020417,  0.43837211,  0.        ,  0.9917559 ]])

### Fancy Indexing

In [74]:
arr = np.empty((8, 4))
arr

array([[  6.92809863e-310,   6.92809863e-310,   1.93101617e-312,
          1.97345609e-312],
       [  1.90979621e-313,   1.10343781e-312,   6.79038653e-313,
          3.18299369e-313],
       [  2.41907520e-312,   1.08221785e-312,   4.45619117e-313,
          2.44029516e-312],
       [  2.05833592e-312,   5.72938864e-313,   1.44295714e-312,
          2.05833592e-312],
       [  7.00258612e-313,   2.56761491e-312,   6.79038653e-313,
          8.27578359e-313],
       [  1.10343781e-312,   6.79038653e-313,   9.54898106e-313,
          2.37663529e-312],
       [  2.35541533e-312,   1.08221785e-312,   2.05833592e-312,
          2.14321575e-312],
       [  1.20953760e-312,   2.05833592e-312,   1.29441743e-312,
          2.12199579e-312]])

In [75]:
# vectorized assignment on EACH row
for i in range(8):
    arr[i] = i

In [76]:
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

Select a subset of the rows in a particular order, pass a list or ndarray of integers specifyng the desired order:

In [77]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [78]:
arr[np.array([4, 3, 0, 6])]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [79]:
arr[[-3, -5, -7]] # Use negative indices select rows from the end

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [80]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

Passing multiple index arrays does something slightly different; it selects a 1D array of elements corresponding to each tuple of indices:

In [81]:
# arr[1, 0]: 4
# arr[5, 3]: 23
# arr[7, 1]: 29
# arr[2, 2]: 10
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

Fancy index to select **rectangular region** formed by selecting a subset of the matrix's rows and columns:

In [82]:
# row index: 1, 5, 7, 2; col index: 0, 3, 1, 2
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [83]:
# Recursive view

temp = arr[[1, 5, 7, 2]]
temp[:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

Use the **np.ix\_()** function, which converts two 1D integer arrays to an indexer that selects the square region:

In [84]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

**Fancy Indexing:** unlike slicing, always copies the data into a new array

### Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping which similarly returns a **view** on the underlying data without copying anything. Arrays have the **transpose()** method and also the special **T** attribute:

In [85]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [86]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Computing $X'X$ using **np.dot()**:

In [87]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[ 9.13892925, -0.73875399, -2.57089642],
       [-0.73875399,  8.67179855,  3.92549855],
       [-2.57089642,  3.92549855,  4.28479322]])

For higher dimensional arrays, **transpose** will accept a tuple of axis numbers to permute the axes

In [88]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [89]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

Simple transposing with **.T** is just a special case of swapping axes. ndarray has the method **swapaxes** which takes a pair of axis numbers:

In [90]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [91]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-wise Array Functions

A universal function, or *ufunc*, is a function that performs elementwise operations on　data in ndarray

In [92]:
arr = np.arange(10)
np.sqrt(arr) # unary ufuncs

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [93]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [94]:
x = np.random.randn(8) 
x

array([ 0.89233611,  0.76926616, -2.24095259, -0.38871386, -0.27915128,
        2.18652489, -1.15926694,  0.7527272 ])

In [95]:
y = np.random.randn(8)
y

array([-0.64935619,  1.06906781,  1.02539769,  0.09752461, -0.05064705,
       -0.02577049, -0.50185061, -0.13177574])

In [96]:
np.maximum(x, y) # binary ufuncs

array([ 0.89233611,  1.06906781,  1.02539769,  0.09752461, -0.05064705,
        2.18652489, -0.50185061,  0.7527272 ])

While not common, a ufunc can return multiple arrays. **modf** is one example, a vectorized version of the built-in Python **divmod** : it returns the fractional and integral parts of a floating point array:

In [97]:
arr = np.random.randn(7) * 5
arr

array([-11.54745105,  -5.52087719,   0.86614397,  10.32628857,
        -4.66262885,  -1.68339823, -13.96380767])

In [98]:
np.modf(arr)

(array([-0.54745105, -0.52087719,  0.86614397,  0.32628857, -0.66262885,
        -0.68339823, -0.96380767]),
 array([-11.,  -5.,   0.,  10.,  -4.,  -1., -13.]))

In [99]:
# Unary ufuncs
np.abs(x)

np.sqrt(np.abs(x))

np.square(x)

np.exp(x)

np.exp(np.abs(x))

np.log(np.abs(x))

np.sign(x)

np.ceil(x)

np.rint(x) # round to nearest integer

np.floor(x)

np.modf(arr)

np.isnan(x)

np.isfinite(x)

np.isinf(x)

np.logical_not(x, y)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [100]:
np.add(x, y) # x + y

np.subtract(x, y) # x - y

np.multiply(x, y) # x * y

np.divide(x, y) # x / y

np.power(np.abs(x), y)

np.maximum(x, y) # Element-wise maximum

np.mod(x, y) # Element-wise modulus

np.greater(x, y) # x > y

np.less_equal(x, y) # x <= y

np.not_equal(x, y)

np.logical_and(x, y) # when x, y are bool array

/home/jichao/.local/lib/python2.7/site-packages/ipykernel/__main__.py:7: RuntimeWarning: divide by zero encountered in divide
/home/jichao/.local/lib/python2.7/site-packages/ipykernel/__main__.py:13: RuntimeWarning: invalid value encountered in remainder


array([False, False, False, False, False, False, False, False], dtype=bool)

## Data Processing Using Arrays

Vectorized array operations will often be one or two (or more) orders of magnitude faster than their pure Python equivalents.

The **np.meshgrid** function takes two 1D arrays and produces two 2D matrices corresponding to all pairs of **(x, y)** in the two arrays:

In [101]:
points = np.arange(-5, 5, 0.01) # 1000 equally spaced points
xs, ys = np.meshgrid(points, points)

In [102]:
import matplotlib.pyplot as plt
z = np.sqrt(xs ** 2 + ys ** 2)
z.shape

(1000, 1000)

In [103]:
plt.imshow(z, cmap=plt.cm.gray)
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")
plt.show()

### Expressing Conditional Logic as Array Operations

The **numpy.where()** function is a vectorized version of the ternary expression **x if condition else y**.

In [104]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

This has multiple problems. First, it will not be very fast for large arrays (because all the work is being done in pure Python). Secondly, it will not work with multidimensional arrays. With **np.where()** you can write this very concisely:

In [105]:
result = np.where(cond, xarr, yarr)
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

The second and third arguments to np.where don't need to be arrays; one or both of them can be scalars.

A typical use of **where** in data analysis is to produce a new array of values based on another array. Suppose you had a matrix of randomly generated data and you wanted to replace all positive values with 2 and all negative values with -2.

In [106]:
arr = np.random.randn(4, 4)
arr

array([[ 1.11459785,  0.67809045,  1.97484722,  1.38637298],
       [ 1.10485392, -0.47077455,  0.35025875, -0.96663347],
       [-0.63354279, -0.88931331, -0.56273507, -0.87864814],
       [-1.43059355,  0.7886933 , -0.29692778, -0.46856709]])

In [107]:
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2,  2],
       [ 2, -2,  2, -2],
       [-2, -2, -2, -2],
       [-2,  2, -2, -2]])

In [108]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        ,  2.        ,  2.        ,  2.        ],
       [ 2.        , -0.47077455,  2.        , -0.96663347],
       [-0.63354279, -0.88931331, -0.56273507, -0.87864814],
       [-1.43059355,  2.        , -0.29692778, -0.46856709]])

With some cleverness you can use **where** to express more complicated logic; consider this example where I have two boolean arrays, **cond1** and **cond2**, and wish to assign a different value for each of the 4 possible pairs of boolean values:

In [109]:
cond1 = np.array([True, False, False, True])
cond2 = np.array([False, False, True, True])

result = []
for i in range(4):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)
        
result        

[1, 3, 2, 0]

In [110]:
np.where(cond2, 2, 3)

array([3, 3, 2, 2])

In [111]:
np.where(cond1, 1, np.where(cond2, 2, 3))

array([1, 3, 2, 1])

In [112]:
np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))

array([1, 3, 2, 0])

### Mathematical and Statistical Methods

Aggregations (often called *reductions*) like sum, mean, and standard deviation std can either be used by calling the array instance method or using the top level NumPy function:

In [113]:
arr = np.random.randn(5, 4)
arr

array([[-0.15145067, -1.41416166, -0.18595448,  1.7931946 ],
       [-2.09966925,  2.33504742, -0.9938787 , -0.36572717],
       [-1.26645377, -0.39308187, -0.04535728,  0.41421483],
       [-0.71652655,  0.8150377 , -0.26179729,  0.13611972],
       [ 0.27931623, -1.04994051,  0.60232953, -0.45549886]])

In [114]:
arr.mean()

-0.15121190277802957

In [115]:
np.mean(arr)

-0.15121190277802957

In [116]:
arr.sum()

-3.0242380555605912

Functions like **mean** and **sum** take an optional **axis** argument which computes the statistic over the given axis, resulting in an array with one fewer dimension:

In [117]:
arr.mean(axis=1)

array([ 0.01040695, -0.28105693, -0.32266952, -0.00679161, -0.1559484 ])

In [118]:
np.mean(arr[0])

0.010406945119693312

In [119]:
arr.mean(axis=0)

array([-0.7909568 ,  0.05858021, -0.17693165,  0.30446062])

In [120]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Other methods like **cumsum** and **cumprod** do not aggregate, instead producing an array of the intermediate results:

In [121]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [122]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [123]:
arr = np.random.randint(0, 9, size=(3, 3))
arr

array([[6, 0, 0],
       [0, 6, 1],
       [8, 5, 4]])

In [124]:
arr.argmin(axis=0) # Indices of minimum

array([1, 0, 0])

In [125]:
arr.argmax(axis=1) #  Indices of maximum

array([0, 1, 0])

### Methods for Boolean Arrays

Boolean values are coerced to 1 (**True**) and 0 (**False**) in the above methods. Thus, **sum** is often used as a means of counting **True** values in a boolean array

In [126]:
arr = np.random.randn(100)
len(arr[(arr > 0) == True])

46

In [127]:
(arr > 0).sum()

46

**any** tests whether one or more values in an array is True, while **all** checks if every value is True :

In [128]:
bools = np.array([False, False, True, False])
bools.any()

True

In [129]:
bools.all()

False

### Sorting

NumPY arrays can be sorted in-place using the **sort()** method:

In [130]:
arr = np.random.randn(8)
arr

array([-1.98378027,  0.16595017, -0.1853596 , -0.32551164, -0.73366916,
        0.63870078,  0.43606001, -1.70720871])

In [131]:
arr.sort()
arr

array([-1.98378027, -1.70720871, -0.73366916, -0.32551164, -0.1853596 ,
        0.16595017,  0.43606001,  0.63870078])

In [132]:
arr = np.random.randn(5, 3)
arr

array([[-0.41865159,  0.2511971 , -0.64299411],
       [-1.89149623,  0.06805467, -0.93139492],
       [-1.43938114,  2.003948  ,  1.7032675 ],
       [-1.22634759,  1.21282416,  0.26617673],
       [-0.75605524, -0.67500111, -0.11972497]])

Multidimensional arrays can have each 1D section of values sorted in-place along an axis by passing the axis number to sort :

In [133]:
arr.sort(axis=1)
arr

array([[-0.64299411, -0.41865159,  0.2511971 ],
       [-1.89149623, -0.93139492,  0.06805467],
       [-1.43938114,  1.7032675 ,  2.003948  ],
       [-1.22634759,  0.26617673,  1.21282416],
       [-0.75605524, -0.67500111, -0.11972497]])

The top level method **np.sort()** returns a sorted copy of an array instead of modifying the array in place

In [134]:
np.sort(arr[0])

array([-0.64299411, -0.41865159,  0.2511971 ])

In [135]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 0.05 percentile

-1.6584559357897541

In [136]:
np.percentile(large_arr, 5)

-1.6585754735202891

### Unique and Other Set Logic

In [137]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], 
      dtype='|S4')

In [138]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [139]:
sorted(set(names))

['Bob', 'Joe', 'Will']

Another function, **np.in1d()**, tests membership of the values in one array in another, returning a boolean array:

In [140]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True], dtype=bool)

### File Input and Output with Arrays

NumPy is able to save and load data to and from disk either in text or binary format.

#### Storing Arrays on Disk in Binary Format

**np.save()** and **np.load()** are the two workhorse functions for efficiently saving and loading array data on disk. Arrays are saved by default in an uncompressed raw binary format with file extension **.npy**.

In [141]:
arr = np.arange(10)
np.save('some_array', arr)

In [142]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

You save multiple arrays in a zip archive using **np.savez** and passing the arrays as key-word arguments:

In [143]:
np.savez('array_archive.npz', a=arr, b=arr)

When loading an **.npz** file, you get back a dict-like object which loads the individual arrays lazily:

In [144]:
arch = np.load('array_archive.npz')
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Saving and Loading Text Files

In [145]:
!cat array_ex.txt

0.580052,0.186730,1.040717,1.134411
0.194163,-0.636917,-0.938659,0.124094
-0.126410,0.268607,-0.695724,0.047428
-1.484413,0.004176,-0.744203,0.005487
2.302869,0.200131,1.670238,-1.881090
-0.193230,1.047233,0.482803,0.960334


In [146]:
arr = np.loadtxt('array_ex.txt', delimiter=',')
arr

array([[ 0.580052,  0.18673 ,  1.040717,  1.134411],
       [ 0.194163, -0.636917, -0.938659,  0.124094],
       [-0.12641 ,  0.268607, -0.695724,  0.047428],
       [-1.484413,  0.004176, -0.744203,  0.005487],
       [ 2.302869,  0.200131,  1.670238, -1.88109 ],
       [-0.19323 ,  1.047233,  0.482803,  0.960334]])

## Linear Algebra

The function **dot()** , both an array method, and a function in the numpy namespace, computes matrix multiplication:

In [147]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [148]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[  6.,  23.],
       [ -1.,   7.],
       [  8.,   9.]])

In [149]:
x.dot(y) # equivalently np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

In [150]:
np.dot(x, y)

array([[  28.,   64.],
       [  67.,  181.]])

A matrix product between a 2D array and a suitably sized 1D array results in a 1D array:

In [151]:
np.dot(x, np.ones(3))

array([  6.,  15.])

**numpy.linalg** has a standard set of matrix decompositions and things like inverse and determinant.

In [152]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)
inv(mat)

array([[ 0.33019938,  0.32453285,  0.75279098,  0.22119935, -0.92078472],
       [ 0.32453285,  1.47788236,  2.97863688,  0.93311673, -3.35939173],
       [ 0.75279098,  2.97863688,  6.58388721,  1.77007594, -7.09788658],
       [ 0.22119935,  0.93311673,  1.77007594,  0.84335499, -2.18760227],
       [-0.92078472, -3.35939173, -7.09788658, -2.18760227,  8.27234292]])

In [153]:
mat.dot(inv(mat))

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [ -1.11022302e-15,   1.00000000e+00,   1.77635684e-15,
         -1.77635684e-15,   0.00000000e+00],
       [ -4.44089210e-16,  -8.88178420e-16,   1.00000000e+00,
         -8.88178420e-16,   3.55271368e-15],
       [  2.22044605e-16,  -1.77635684e-15,   0.00000000e+00,
          1.00000000e+00,   1.77635684e-15],
       [  4.44089210e-16,   0.00000000e+00,   0.00000000e+00,
         -8.88178420e-16,   1.00000000e+00]])

In [154]:
q, r = qr(mat)

## Random Number Generation

The **numpy.random** module supplements the built-in Python **random** with functions for efficiently generating whole arrays of sample values from many kinds of probability distributions. For example, you can get a 4 by 4 array of samples from the standard normal distribution using **normal**:

In [155]:
samples = np.random.normal(loc=0.0, scale=1.0, size=(4,4))
samples

array([[-1.9471424 ,  0.29080906, -0.17106591, -0.59121987],
       [-0.38383139,  1.19122826, -0.44027594,  1.59829059],
       [-0.88003009,  0.29784051,  0.18541146, -0.60569148],
       [ 0.49544709, -1.21580255,  1.28550483, -0.71724551]])

Python's built-in **random** module, by contrast, only samples one value at a time. As you can see from this benchmark, **numpy.random** is well over an order of magnitude faster for generating very large samples:

In [156]:
from random import normalvariate

N = 1000000
%timeit samples = [normalvariate(0, 1) for i in xrange(N)] # slow
%timeit np.random.normal(size=N) # fast

1 loop, best of 3: 777 ms per loop
10 loops, best of 3: 38 ms per loop


In [157]:
arr = np.arange(10)

In [158]:
np.random.permutation(arr) # Return a random permutation of a sequence

array([9, 6, 0, 1, 4, 3, 5, 7, 2, 8])

In [159]:
np.random.permutation(10) # Or return a permuted range

array([3, 2, 9, 8, 7, 4, 5, 6, 1, 0])

In [160]:
np.random.shuffle(arr) # Randomly permute a sequence in place
arr

array([2, 3, 4, 5, 8, 1, 7, 9, 6, 0])

## Example: Random Walks

In [161]:
import random
position = 0
walk = [position]
steps = 100
for i in xrange(steps):
    step = 1 if random.randint(0, 1) else -1 # Python' random model, '1' is inclusive 
    position += step
    walk.append(position)

In [162]:
plt.plot(walk); plt.show()

In [163]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
steps = np.where(draws > 0, 1, -1)
walk = steps.cumsum()
walk.min()

-13

In [164]:
walk.max()

28

In [165]:
(np.abs(walk) >= 10).argmax()

57

In [166]:
plt.plot(walk)
plt.show()

### Simulating Many Random Walks at Once

In [167]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(axis=1)

In [168]:
walks

array([[ -1,  -2,  -3, ..., -14, -15, -14],
       [ -1,  -2,  -1, ..., -30, -29, -30],
       [  1,   0,   1, ...,  10,   9,   8],
       ..., 
       [  1,   0,  -1, ..., -64, -63, -64],
       [  1,   2,   3, ...,  28,  29,  30],
       [ -1,   0,  -1, ..., -22, -21, -20]])

In [169]:
walks.shape

(5000, 1000)

In [170]:
walks.max()

142

In [171]:
walks.min()

-117

In [172]:
hits30 = (np.abs(walks) >= 30).any(1)
hits30

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [173]:
hits30.sum()

3428

In [174]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times.shape

(3428,)

In [175]:
crossing_times.mean()

507.40256709451575